name: Pylint

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
      
    - name: Clone cares_reinforcement_learning repository
      uses: GuillaumeFalourd/clone-github-repo-action@main
      with:
        owner: 'UoA-CARES'
        repository: 'cares_reinforcement_learning'
    
    - name: Install cares_reinforcement_learning repository content
      run: |
        cd cares_reinforcement_learning
        pip install -r requirements.txt
        pip install --editable .
        cd -

    - name: Install deps
      run: |
        pip install -r requirements.txt

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --disable=logging-fstring-interpolation \
                                      --disable=too-few-public-methods \
                                      --disable=missing-module-docstring \
                                      --disable=missing-function-docstring \
                                      --disable=missing-class-docstring \
                                      --disable=too-many-locals \
                                      --disable=W0511 \
                                      --disable=too-many-arguments \
                                      --max-line-length 130 \
                                      --extension-pkg-whitelist=cv2 --generated-members=cv2.* \
                                      --fail-under 9 --fail-on E